#ifndef PP2_PAINTBALL_DEFINES_H
#define PP2_PAINTBALL_DEFINES_H

#define PP2_PAINTBALL_TYPE_NORMAL     0
#define PP2_PAINTBALL_TYPE_SPLITTER   1
#define PP2_PAINTBALL_TYPE_MINE       2
#define PP2_PAINTBALL_TYPE_BOUNCER    3
#define PP2_PAINTBALL_TYPE_SEEKER     4
#define PP2_PAINTBALL_TYPE_REFLECTOR  5
#define PP2_PAINTBALL_TYPE_PMINE      6
#define PP2_PAINTBALL_TYPE_GHOST      7

#define PP2_PAINTBALL_FLAG_ACTIVE     1
#define PP2_PAINTBALL_FLAG_LANDB      4
#define PP2_PAINTBALL_FLAG_LANDT      8
#define PP2_PAINTBALL_FLAG_LANDL     16
#define PP2_PAINTBALL_FLAG_LANDR     32

#define PP2_PAINTBALL_TRAIL_TIME      6
#define PP2_PAINTBALL_HIGHLIGHT_SIZE  4

#endif
